//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.DatHangCts = new HashSet<DatHangCt>();
            this.TrinhBays = new HashSet<TrinhBay>();
        }
    
        public int AlbumId { get; set; }
        public string TenAlbum { get; set; }
        public System.DateTime NgayPhatHanh { get; set; }
        public decimal GiaBan { get; set; }
        public string AnhBia { get; set; }
        public string GioiThieu { get; set; }
    
        public virtual ICollection<DatHangCt> DatHangCts { get; set; }
        public virtual ICollection<TrinhBay> TrinhBays { get; set; }
    }
}
