//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHat
    {
        public BaiHat()
        {
            this.TrinhBays = new HashSet<TrinhBay>();
        }
    
        public int BaiHatId { get; set; }
        public string TenBaiHat { get; set; }
        public string LoiBaiHat { get; set; }
        public int TacGiaId { get; set; }
        public int TheLoaiId { get; set; }
    
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        public virtual ICollection<TrinhBay> TrinhBays { get; set; }
    }
}
