//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaSy
    {
        public CaSy()
        {
            this.TrinhBays = new HashSet<TrinhBay>();
        }
    
        public int CaSyId { get; set; }
        public string TenCaSy { get; set; }
        public string TieuSu { get; set; }
        public string Hinh { get; set; }
    
        public virtual ICollection<TrinhBay> TrinhBays { get; set; }
    }
}
