//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        public DatHang()
        {
            this.DatHangCts = new HashSet<DatHangCt>();
        }
    
        public int DatHangId { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public string TenDangNhap { get; set; }
        public string HoKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public decimal TriGia { get; set; }
    
        public virtual ICollection<DatHangCt> DatHangCts { get; set; }
    }
}
