//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHangCt
    {
        public int DatHangCtId { get; set; }
        public int DatHangId { get; set; }
        public int AlbumId { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaBan { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual DatHang DatHang { get; set; }
    }
}
