//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        public TacGia()
        {
            this.BaiHats = new HashSet<BaiHat>();
        }
    
        public int TacGiaId { get; set; }
        public string TenTacGia { get; set; }
    
        public virtual ICollection<BaiHat> BaiHats { get; set; }
    }
}
