//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrinhBay
    {
        public int TrinhBayId { get; set; }
        public int AlbumId { get; set; }
        public int BaiHatId { get; set; }
        public int CaSyId { get; set; }
        public string TenTapTin { get; set; }
        public int LuotNghe { get; set; }
        public int YeuThich { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual BaiHat BaiHat { get; set; }
        public virtual CaSy CaSy { get; set; }
    }
}
